import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { FC, PropsWithChildren } from "react"
import { Providers } from "@/app/providers"
import { Box } from "@chakra-ui/react"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <html lang="ja">
    <body className={inter.className}>
      <Providers>
        <Box as="main" p={4}>
          {children}
        </Box>
      </Providers>
    </body>
  </html>
)

export default RootLayout
